import os
print('Baslıyor')
os.system('pip install pyfiglet')
os.system('pip install selenium')
os.system('pip install requests')
os.system('pip install pyfiglet')
os.system('pip install user_agent')
os.system('pip install TelegramAPI')
os.system('pip install ms4')
os.system('pip install python-cfonts')
os.system('pip install sys')
os.system('pip install uuid')
os.system('pip install types')
os.system('pip install time')
os.system('pip install os')
os.system('pip install random')
os.system('pip install datetime')
os.system('pip install string')
os.system('pip install secrets')
os.system('pip install webbrowser')
os.system('pip install hashlib')
os.system('pip install colorama')
os.system('pip install InstagramAPI')
os.system('pip install generate_user_agent')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install datetime')
os.system('pip install token_hex')
os.system('pip install secrets')
os.system('pip install *')
os.system('pip install new')
os.system('pip install pafy')
os.system('pip install bs4')
os.system('pip install json')
os.system('pip install pillow')
os.system('pip install pyTelegramBotAPI')
os.system('pip install names')
os.system('pip install match')
os.system('pip install InlineKeyboardMarkup')
os.system('cls' if os.name == 'nt' else 'clear') 
print('Bitti')

